//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class JZHZ
    {
        public string ID { get; set; }
        public Nullable<long> NPHONE { get; set; }
        public string VNAME { get; set; }
        public string NSEX { get; set; }
        public string VSFZH { get; set; }
        public string VCARD { get; set; }
        public string VPWD { get; set; }
        public string VPYM { get; set; }
        public Nullable<System.DateTime> DBIRTHDAY { get; set; }
        public Nullable<bool> NSTOP { get; set; }
        public string VPATIENTID { get; set; }
        public Nullable<System.DateTime> DCREATE { get; set; }
    }
}
