//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST11
    {
        public Nullable<System.DateTime> BIRTH_OF_DATE { get; set; }
        public string IDENTITY_ID { get; set; }
        public Nullable<decimal> MARITAL_STATUS_CODE { get; set; }
        public Nullable<decimal> GENDER { get; set; }
        public string FLAGFIELD { get; set; }
        public string PATIENT_ID { get; set; }
        public string NAME { get; set; }
        public string BIRTH_OF_PLACE { get; set; }
        public string NATION_CODE { get; set; }
        public string CITIZENSHIP { get; set; }
    }
}
