//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTTT
    {
        public string VID { get; set; }
        public string VNAME { get; set; }
        public string VSTAFFCODE { get; set; }
        public string VSTAFFNAME { get; set; }
        public string PINYINMA { get; set; }
        public string WUBIMA { get; set; }
        public string VLOGINUSERNAME { get; set; }
        public string VLOGINPASSWORD { get; set; }
        public int NSTAFFSTATUS { get; set; }
        public Nullable<int> NROLEID { get; set; }
        public string VDEPARTCODE { get; set; }
        public int NJOBID { get; set; }
        public int NPROFESSIONID { get; set; }
        public int NOPHZID { get; set; }
        public byte NISDUMA { get; set; }
        public Nullable<System.DateTime> DFHTIME { get; set; }
        public Nullable<System.DateTime> DTHTIME { get; set; }
        public string VTMETHOD { get; set; }
        public string VSCHOOL { get; set; }
        public Nullable<bool> NSEX { get; set; }
        public Nullable<System.DateTime> NBIRTHDAY { get; set; }
        public string VMINZU { get; set; }
        public string VJIGUAN { get; set; }
        public string VXUELI { get; set; }
        public Nullable<byte> NISKSS { get; set; }
    }
}
