//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COST_INFO
    {
        public long NFEE_ID { get; set; }
        public string VCLINICNO { get; set; }
        public string VITEM_NAME { get; set; }
        public System.DateTime DFEE_DATE { get; set; }
        public string VITEM_UNITS { get; set; }
        public Nullable<decimal> NITEM_PRICE { get; set; }
        public Nullable<decimal> NITEM_SL { get; set; }
        public Nullable<decimal> NITEM_MONEY { get; set; }
        public string VDEPARTNAME { get; set; }
        public string VFEE_OPERATENAME { get; set; }
        public Nullable<decimal> NBACK_SL { get; set; }
    }
}
