//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EXAMITEMS_INFO
    {
        public string VEXAM_ID { get; set; }
        public string VPATIENT_ID { get; set; }
        public string VEXAM_POSITION { get; set; }
        public System.DateTime DAPPLY_DATE { get; set; }
        public string VAPPLY_DEPT { get; set; }
        public string VAPPLY_DOCTOR { get; set; }
        public bool NEXAM_RESULT { get; set; }
        public bool MZORZY { get; set; }
        public string VCLINICNO { get; set; }
        public Nullable<System.DateTime> DEXECUTE { get; set; }
        public string EXEDOCTORNAME { get; set; }
        public string VITEMNAME { get; set; }
        public string VUNITS { get; set; }
        public Nullable<byte> NACCOUNT { get; set; }
        public string VNAME { get; set; }
        public string NSEX { get; set; }
        public string NAGE { get; set; }
        public string SQDEPARTNAME { get; set; }
        public string SQDOCTORNAME { get; set; }
        public string VRESULT_DESP { get; set; }
        public string VDIAGNOSE { get; set; }
    }
}
