//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LABITEMS_INFO
    {
        public string VLAB_ID { get; set; }
        public string VITEM_CODE { get; set; }
        public string ITEMNAMEMX { get; set; }
        public string VITEM_NAME { get; set; }
        public string NUNITS { get; set; }
        public Nullable<byte> NACCOUNT { get; set; }
        public string VPATIENT_ID { get; set; }
        public Nullable<System.DateTime> DAPPLY_DATE { get; set; }
        public string VAPPLY_DEPT { get; set; }
        public string VAPPLY_DOCTOR { get; set; }
        public Nullable<bool> NLAB_RESULT { get; set; }
        public Nullable<bool> NFLAG { get; set; }
        public string VCLINICNO { get; set; }
        public Nullable<System.DateTime> DEXECUTE { get; set; }
        public string SQDEPART { get; set; }
        public string SQSTAFFNAME { get; set; }
        public string PATIENTNAME { get; set; }
        public string NSEX { get; set; }
        public string NAGE { get; set; }
        public string EXEDOCTORNAME { get; set; }
    }
}
