//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MZSF_PRESC
    {
        public string VCLINICNO { get; set; }
        public string VNAME { get; set; }
        public string VIDNO { get; set; }
        public string VDEPARTNAME { get; set; }
        public string VDOCTOR_NAME { get; set; }
        public string VPRESC_ID { get; set; }
        public string VITEM_CODE { get; set; }
        public string VITEM_NAME { get; set; }
        public string VUNITS { get; set; }
        public Nullable<decimal> NPRICE { get; set; }
        public Nullable<decimal> NACCOUNT { get; set; }
        public Nullable<decimal> NCOSTS { get; set; }
        public Nullable<System.DateTime> DPRESC_DATE { get; set; }
        public string VDEPT_CODENAME { get; set; }
        public Nullable<decimal> VITEM_TYPE { get; set; }
        public string VITEM_TYPE_NAME { get; set; }
    }
}
