//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MZ_CHARGEDETAIL
    {
        public string VCLINICNO { get; set; }
        public string VDEPARTCODE { get; set; }
        public string VDEPARTNAME { get; set; }
        public string VPRESC_ID { get; set; }
        public string LSH { get; set; }
        public string VDOCTOR_ID { get; set; }
        public string VDOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> DPRESC_DATE { get; set; }
        public string VITEM_CODE { get; set; }
        public string VITEM_NAME { get; set; }
        public Nullable<decimal> NPRICE { get; set; }
        public Nullable<decimal> NSL { get; set; }
        public string VUNITS { get; set; }
        public Nullable<decimal> NCOSTS { get; set; }
        public Nullable<bool> NSTATUS { get; set; }
        public Nullable<int> VTYPEID { get; set; }
        public string VTYPENAME { get; set; }
    }
}
