//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PATIENT_ZY_INFO
    {
        public string VPATIENTID { get; set; }
        public string VCLINICNO { get; set; }
        public string VNAME { get; set; }
        public System.DateTime DVISITDATE { get; set; }
        public string VSEX { get; set; }
        public string VBIRTHDATE { get; set; }
        public string VAGE { get; set; }
        public string VIDNO { get; set; }
        public string VDEPARTNAME { get; set; }
        public Nullable<byte> NAPPTIME { get; set; }
        public Nullable<bool> NSTATUS { get; set; }
    }
}
