//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PATIENT_BASIC_INFO
    {
        public string VPATIENTID { get; set; }
        public string VNAME { get; set; }
        public string VSEX { get; set; }
        public string VBIRTHDATE { get; set; }
        public string VAGE { get; set; }
        public string VIDNO { get; set; }
        public string VBIRTHPLACE { get; set; }
        public string VPRESENTADDRESS { get; set; }
    }
}
