//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_REGPLAN
    {
        public string VPLANID { get; set; }
        public string VDOCTORID { get; set; }
        public Nullable<bool> NTIMEDESC { get; set; }
        public string SJD { get; set; }
        public Nullable<int> NREGLIMITS { get; set; }
        public Nullable<int> NAPPLIMITS { get; set; }
        public Nullable<int> NREGNUMBER { get; set; }
        public Nullable<int> NAPPNUMBER { get; set; }
        public System.DateTime DCLINICDATE { get; set; }
        public string VDEPTID { get; set; }
        public Nullable<int> NHOSID { get; set; }
        public string GHF { get; set; }
        public string ZLF { get; set; }
        public string HAOBIE { get; set; }
        public string VDEPARTNAME { get; set; }
    }
}
