//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_PEINFO
    {
        public string VPEID { get; set; }
        public string VNAME { get; set; }
        public Nullable<bool> NSEX { get; set; }
        public string NSEXNAME { get; set; }
        public string VIDNO { get; set; }
        public System.DateTime DPEDATE { get; set; }
        public System.DateTime DLASTPEDATE { get; set; }
        public string VPEGROUPNAME { get; set; }
        public Nullable<decimal> NSTATUS { get; set; }
    }
}
