//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_PACKAGE
    {
        public int NPACKAGEID { get; set; }
        public string VPEGROUPNAME { get; set; }
        public string PINYINMA { get; set; }
        public decimal NVPRICE { get; set; }
        public decimal NDISCOUNTS { get; set; }
        public decimal NMONEY { get; set; }
        public string VDESCRIPTION { get; set; }
    }
}
