//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_PETIME
    {
        public string VPEID { get; set; }
        public int NITEMID { get; set; }
        public string VITEMNAME { get; set; }
        public Nullable<int> NPACKAGEID { get; set; }
        public decimal NMONEY { get; set; }
        public string VITEMADDRESS { get; set; }
        public Nullable<bool> HISNITEMTYPE { get; set; }
    }
}
